test/style/blocks_test.exs, test/style/configs_test.exs, test/style/defs_test.exs, test/style/deprecations_test.exs, test/style/module_directives_test.exs, test/style/pipes_test.exs, test/style/single_node_test.exs, test/style/styles_test.exs, test/style_test.exs, test/zipper_test.exs
This is not the best solution ever, but it's the fastest fix to eliminate flakiness. Tests don't take long even with all being synchronous. If we get to a point where tests are taking a long time, we can consider a different approach.
closes #24
=> Make tests sync to eliminate flakiness

README.md, lib/quokka/config.ex
Preserving the original newlines turns out to be very non-trivial... though perhaps there is some secret sauce with walking ASTs that I'm unaware of that enables one to preserve the original formatting.
Until/unless that is discovered, this is a middle ground that lets you do all the newline fixes in one fell swoop before enabling Quokka wholesale.
For anyone wondering or interested in taking a look, [here](https://github.com/smartrent/quokka/blob/main/lib/styler.ex#L108) is the line responsible for shrinking down newlines (it took me far too long to figure out it wasn't a standard AST transformation elsewhere in the repo 🤦)
=> Introduce a newline only mode

README.md, docs/mix_configs.md, lib/quokka/config.ex, test/config_test.exs
Breaking config change, but it allows us to phase in Quokka much more easily.
=> Feature: Explicitly pick style fixups with :only & :exclude

.formatter.exs, README.md, docs/styles.md, lib/quokka/config.ex, lib/styler.ex, test/config_test.exs, test/test_helper.exs
There are 2 ideas of how this could be implemented:
1. Pass formatter opts to Quokka.Config.set/1 (how I did in this PR)
2. Add formatter_opts as a key to styler_opts (example below)
Closes https://github.com/smartrent/quokka/issues/46
```elixir
styler_opts = [{:__formatter_opts__, formatter_opts} | styler_opts]
Quokka.Config.set(styler_opts)
```
```elixir
def set!(config \\ []) do
...
%{
...,
line_length: credo_opts[:line_length] || config[:__formatter_opts__][:line_length] || 98
}
end
```
Comment out which one you like more
=> feat: respect .formatter.exs line_length

lib/style/pipes.ex, test/style/pipes_test.exs
I've noticed that pipe chain start rule isn't respected for namespaces that are excluded from alias lifting rule:
For example:
stub(Quokka.Config, :lift_alias_excluded_namespaces, fn -> MapSet.new([:Name]) end)
```elixir
defmodule MyModule do
alias Foo.Bar
Name.M.N.bar(x)
|> Name.M.N.bar()
A.B.C.foo()
end
```
currently refactors to
```elixir
defmodule MyModule do
alias A.B.C
alias Foo.Bar
Name.M.N.bar(x)
|> Name.M.N.bar()
C.foo()
end
```
and I was assuming it'd refactor to:
```elixir
defmodule MyModule do
alias A.B.C
alias Foo.Bar
x
|> Name.M.N.bar()
|> Name.M.N.bar()
C.foo()
end
```
I was imagining that the alias lifting excluded namespaces shouldn't fail and proposing an example fix
closes #68
=> [Fix] Fix pipe chain start with alias lifting exceptions

README.md, docs/single_node.md, lib/style/single_node.ex, test/style/single_node_test.exs
This adds rewrites for unnecessarily expensive checks of an enum's emptiness, like `length(enum) == 0`.
While I handled cases where you pipe to `length/1`/`Enum.count/1` and check equality to 0, I intentionally did not rewrite the cases where you pipe to length/count and then check if the result is greater than zero:
```elixir
if foo |> bar() |> length() > 0 do
"not empty"
else
"empty"
end
```
Wrapping the whole pipe in a `not` seemed too ugly, and I am predisposed to avoid piping into `Kernel.not/1`. 😆
=> Add rewrites for Credo's ExpensiveEmptyEnumCheck

mix.exs
Adds a "Changelog" link to the package metadata that will display on hex.pm. This makes it easier for users to find version history directly from the package page.
The changelog link points to the CHANGELOG.md file in the GitHub repository using the existing `@url` module attribute.
=> Add changelog link to Hex package metadata

lib/styler.ex
Hey! 
I noticed our ignored files were no longer being formatted at all because the plugin system [replaces the default formatter](https://github.com/elixir-lang/elixir/blob/e3f7759fded70267560ecf17cbdc2b2d3b482753/lib/mix/lib/mix/tasks/format.ex#L702).
This change runs the normal [elixir_format](https://github.com/elixir-lang/elixir/blob/e3f7759fded70267560ecf17cbdc2b2d3b482753/lib/mix/lib/mix/tasks/format.ex#L751) logic on files that are ignored at the quokka level.
I have not found time to add an automated test to this PR, but let me know if that is something you would like!
=> Run formatter on ignored files

README.md, docs/comment_directives.md, lib/quokka/config.ex, lib/style/comment_directives.ex, test/style/comment_directives_test.exs
Closes #74 
I'm a little concerned that this is too crude a way to detect an Ecto query, but it may be good enough. I think the risk is relatively low -- worst case scenario, some things that should get autosorted will not be, and I can address those bugs as they come up. The other risk is that if a query is described as the following, then the `select` will still get autosorted -- but there's only so much I can engineer for:
```
select_map = %{name: name, email: email}
my_query = from u in users, select: ^select
```
=> Skip autosort for ecto queries

README.md, docs/styles.md, lib/quokka/config.ex
As per #85, I'm consolidating the config so that `inefficient_function_rewrites` and `piped_function_exclusions` are no longer standalone exclusions. I want to move towards the pattern of having exclusions in the `exclusion` list. For now, support both formats but warn users that the original approach is deprecated.
=> Deprecate piped_function_exclusions and inefficient_function_rewrites

lib/style/single_node.ex, test/style/single_node_test.exs
```elixir
assert Repo.one(query)
assert Repo.exists?(query)
```
This one has been bugging me for a while :)
=> Rewrite inefficient Repo existence checks

lib/style/tests.ex, test/style/tests_test.exs
Similar to https://github.com/emkguts/quokka/pull/94, it would be beneficial to rewrite:
- `refute not` -> `assert`
- `refute !` -> `assert`
for symmetry
=> Rewrite refute not... to assert

lib/quokka/config.ex
When running in a language server context, it's possible that the version isn't set in the project. Similarly, there are other contexts where you might want to use Quokka (like as a library).
The current version parsing relies on the project existing and its elixir version being set. If the latter isn't true, then the current code returns nil, which causes the regex match to fail.
This fixes the failure by defaulting to an empty string, which will cause the system version to be used.
=> [fix] The project elixir isn't always present

lib/style/pipes.ex, test/style/pipes_test.exs
It'd be nice to auto rewrite the following cases:
1. Consecutive Map.deletes to single Map.drop
From
```elixir
x
|> Map.delete(key1)
|> Map.delete(key2)
```
to
```elixir
x
|> Map.drop([key1, key2])
```
2. Consecutive Map.drops to single Map.drop
From
```elixir
x
|> Map.drop([key1, key2])
|> Map.drop([key3, key4])
```
to
```elixir
x
|> Map.drop([key1, key2, key3, key4])
```
3. Consecutive Map.delete, Map.drop (or vice-versa) to single Map.drop
From
```elixir
x
|> Map.delete(key1)
|> Map.drop([key2, key3])
```
to
```elixir
x
|> Map.drop([key1, key2, key3])
```
If this approach sounds good, I'd love to update any docs needed and later, put up a followup PR for Keyword as well.
=> Map.drop & Map.delete piping auto-rewrites

lib/style/module_directives.ex, test/style/module_directives_test.exs
Hi Quokka team!
This small PR addresses an issue that I am facing with dealiasing for moduledocs when the alias is above it in the module layout.
If I set the following order:
```
alias
moduledoc
```
The following happens:
```elixir
defmodule Foo do
alias Foo.Bar
@moduledoc "A documentation with some #{Bar}"
end
defmodule Foo do
alias Foo.Bar
@moduledoc "A documentation with some #{Foo.Bar}"
end
```
Ideally, Quokka should consider the order and not dealias if it is not needed:
```elixir
defmodule Foo do
alias Foo.Bar
@moduledoc "A documentation with some #{Bar}"
end
defmodule Foo do
alias Foo.Bar
@moduledoc "A documentation with some #{Bar}"
end
```
Please let me know what you think, and feel free to suggest changes or merge this PR.
=> Conditionally dealias of behaviour, moduledoc, shortdoc

.github/pull_request_template.md
Per [the docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), this should automatically appear in future PRs, saving us a little time looking for the basics.
=> Include a PR template

docs/styles.md, lib/style/single_node.ex, test/style/single_node_test.exs
Rewrites something like `Enum.filter(my_enum, &my_function(&1))` => `Enum.filter(my_enum, &my_function/1)`
=> Rewrite inefficient anonymous functions

lib/style/module_directives.ex, test/style/module_directives_test.exs
=> fix: strict module layout styling fails for non-existent keys

docs/styles.md, lib/style/single_node.ex, test/style/single_node_test.exs
Followup to #110
This was previously crashing trying to rewrite this (admittedly goofy) code:
```elixir
admin? = fn %{user_id: user_id} ->
...
end
Enum.any?(users, &admin?.(&1))
```
=> Handle rewriting anonymous function captures of variables

lib/style/single_node.ex, test/style/single_node_test.exs
This fixes an incorrect rewrite I found in my codebase where we had a bunch of functions that rewrote a string like this:
```elixir
remove_newlines = &String.replace(&1, "\n", "")
remove_dashes = &String.replace(&1, "-", "")
```
...and then we reduced over all the functions like this:
```elixir
Enum.reduce([remove_newlines, remove_dashes], str_to_modify, & &1.(&2))
```
This, of course, is saying to pass the accumulated string into each of the functions in turn. It was being rewritten, though, to just:
```elixir
Enum.reduce([remove_newlines, remove_dashes], str_to_modify, &1)
```
...which is invalid.
=> Fix inefficient function rewrites on Map.reduce arguments

docs/styles.md, lib/style/single_node.ex, test/style/single_node_test.exs
```elixir
Map.get(lhs, key, nil)
lhs |> Map.get(key, nil)
Keyword.get(lhs, key, nil)
lhs |> Keyword.get(key, nil)
Map.get(lhs, key)
lhs |> Map.get(key)
Keyword.get(lhs, key)
lhs |> Keyword.get(key)
```
Can't rewrite Map.get(x, val, nil) to x[val] in case x is a struct since it doesn't implement Access protocol.
=> Rewrite Map/Keyword.get(lhs, key, nil) to Map/Keyword.get(lhs, key)
